import {Hexagon} from '@/_components';
import {Navbar} from '@/_navigation';
import Head from 'next/head';
import {useRouter} from 'next/router';
import React, {memo} from 'react';

// eslint-disable-next-line react/display-name
const Home = memo(() => {
   const router = useRouter();

   return (
      <div className="body">
         <Head>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <title>Goodnews Ogechukwu Ike | Front-End Engineer</title>
            <meta name="description" content="Generated by create next app" />
            <meta property="og:url" content="https://goodnewsike.com/" />
            <meta property="og:title" content="Goodnews Ike Portfolio Website" />
            <meta property="og:description" content="Goodnews Ike Portfolio Website, developer portfolio, frontend portfolio" />
            <meta property="og:type" content="website" />
            <meta name="author" content="Goodnews Ogechukwu Ike" />
            <meta name="keywords" content="Goodnews Ogechukwu Ike, software developer, frontend engineer, frontend, developer" />
            <meta property="og:locale" content="en-US" />
            <meta property="og:type" content="website" />
            <meta name="description" content="Hi, I&#x27;m Goodnews Ogechukwu Ike, Software Developer and Frontend Engineer." />
            <meta property="og:description" content="Hi, I&#x27;m Goodnews Ogechukwu Ike, Software Developer and Frontend Engineer." />

            <meta name="twitter:card" content="summary_large_image" />
            <meta name="mobile-web-app-capable" content="yes" />
            {/* <meta name="msapplication-config" content="/icons/browserconfig.xml" /> */}
            {/* <meta name="twitter:site" content="@code_wonders" />
            <meta name="twitter:image" content="https://i.ibb.co/jz5Qwx1/Group-7.png" /> */}
            {/* <link rel="preload" as="style" href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" /> */}
            {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin /> */}
            {/* <link rel="preconnect" href="https://i.ibb.co/" crossOrigin /> */}
            <link rel="shortcut icon" href="/favicon.ico" />
            {/* <link rel="apple-touch-icon" sizes="57x57" href="/icons/apple-icon-57x57.png" />
            <link rel="apple-touch-icon" sizes="60x60" href="/icons/apple-icon-60x60.png" />
            <link rel="apple-touch-icon" sizes="72x72" href="/icons/apple-icon-72x72.png" />
            <link rel="apple-touch-icon" sizes="76x76" href="/icons/apple-icon-76x76.png" />
            <link rel="apple-touch-icon" sizes="114x114" href="/icons/apple-icon-114x114.png" />
            <link rel="apple-touch-icon" sizes="120x120" href="/icons/apple-icon-120x120.png" />
            <link rel="apple-touch-icon" sizes="144x144" href="/icons/apple-icon-144x144.png" />
            <link rel="apple-touch-icon" sizes="152x152" href="/icons/apple-icon-152x152.png" />
            <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-icon-180x180.png" />
            <link rel="icon" type="image/png" sizes="192x192" href="/icons/android-icon-192x192.png" />
            <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32x32.png" />
            <link rel="icon" type="image/png" sizes="96x96" href="/icons/favicon-96x96.png" />
            <link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon-16x16.png" />
            <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="manifest" href="/manifest.json" />
            <meta name="robots" content="index, nofollow" />
            <link
               rel="author"
               href="https://lh3.googleusercontent.com/KUg3rbUWiVpV83Sdsy5FcsGeOlpcOgi1o3wLhcZGmGkjDmWCj4Hh4kLEEn_1b4dGsm9hzW7lGGvEsUpH2wpCRk9vlfod3ojbJyG7Rdb3ViBaBric9MwvP6J422dIifjzdT4gMJdKkWB4TIlfouuwVm9lxBgxoXEoGm3yiF7xMtFPNIEOTbbgG-WcV6I6jGhLj4AKoRJS_M2g2m5g132WKRTgWSLO4D4sL05lRPAATNq2h3bD72vFGm_Zk-r53dJGBe7FlHIcTV6rU85XD7wwF5sKtmddNbO9nbKg1L-W5pGcU-Ntvx9ayUmxMmGck0FXhf3saN6Qys_dh_C31jy1StMNeceswq1cH8712PvVmca1uNircDdNUbgKIstcn2Q3Egw1w_P5fJ17H6Ru7ZB8gmgEtivx8enUeE_TknyYz37p71GEGCg9-E2m5bl9YaUNTnODjQ2Lh8xeXYnsnCFkvw-XTlWFi799mxtjQFbPK32oAbV728dCld7eB8oTcvB4msAah-hukPKOr83q4GeiZlUe-w_L9hXzFDXF5d86CQbD7ypeUnlhdMaZi8KXOXrkEUMD_njXWSFEh9Xdcnt87Yvkz7VqRxbDHUz4Nid5oiUFAYtUgV917fg1PHroY1Iy0R3g97GXAxHsVc0PfzKLcKgZvoDVURscN8jlpDvbwGfiJ_4HwRHFRys=w1080-h1440-no"
            /> */}
            <meta property="og:title" content="Goodnews Ogechukwu Ike" />
            {/* <meta property="og:url" content="https://codewonders.dev" /> */}
            {/* <meta property="og:image" content="https://i.ibb.co/jz5Qwx1/Group-7.png" /> */}
            <meta name="apple-mobile-web-app-title" content="Goodnews Ogechukwu Ike" />
            {/* <meta name="next-head-count" content="21" /> */}
         </Head>
         <Navbar />
         <main className="container-fluid wrapper position-relative">
            <Hexagon />

            <section className="container p-0 h-100">
               <div className="hero__section d-flex align-items-center justify-content-center">
                  <div className="welcome d-flex flex-column align-items-center justify-content-center">
                     <p className="intro">Hello, I&apos;m</p>
                     <h1 className="name pt-1 text-uppercase">goodnews ike</h1>
                     <h5 className="occupation text-uppercase py-2">Front-End Engineer</h5>
                     <p className="description py-3 text-center">
                        My job is to develop inspiring and exceptionally beautiful user experience for you, so that you can attract more
                        clients/partners and achieve your goal in time.
                     </p>
                     <button onClick={() => router.push('/contact')} className="mt-4 text-uppercase">
                        hire me
                     </button>
                  </div>
               </div>
            </section>
         </main>

         {/* <div className="socialHandles h-100 position-fixed d-flex align-items-center justify-content-center">
        <ul className="social__handles">
          {socialHandles.map<JSX.Element>((item: NavMap) => (
            <a
              key={`socialHandle__fullScreen-${item.id}`}
              href={item.link}
              target="_blank"
              rel="noreferrer"
              className="my-3">
              <li className="">
                {item.icon}
              </li>
            </a>
          ))}
        </ul>
      </div> */}
      </div>
   );
});

export default Home;
